const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones 55",
    image: "/images/airpods.jpeg",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 12999.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    isFeatured: false,
  },
  {
    _id: "2",
    name: "iPhone 12 (Blue 256gb)",
    image: "/images/iphone12.jpeg",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 79999.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    isFeatured: false,
  },
  {
    _id: "3",
    name: "Macbook Air M1",
    image: "/images/macbook.jpeg",
    description:
      "Characterized by versatile imaging specs, the Laptop further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Apple",
    category: "Electronics",
    price: 83999.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
    isFeatured: false,
  },
  {
    _id: "4",
    name: "Sony Tablet",
    image: "/images/tablet.jpeg",
    description:
      "The ultimate home entertainment center starts with Sony Tablet. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    category: "Electronics",
    price: 23999.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
    isFeatured: false,
  },
  {
    _id: "5",
    name: "Samsung Galaxy A21s 128gb",
    image: "/images/samsung_galaxy.jpg",
    description:
      "Get a better handle on your games with this android mobile. The smart gaming processor and 8gb ram customization for a smooth playing experience",
    brand: "Samsung",
    category: "Electronics",
    price: 23299.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
    isFeatured: false,
  },
  {
    _id: "6",
    name: "Apple Homepod smooth sound",
    image: "/images/homepod.jpeg",
    description:
      "Meet Apple Homepod - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Apple",
    category: "Electronics",
    price: 33399.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
    isFeatured: false,
  },
  {
    _id: "7",
    name: "Diwali Sale Samsung",
    image: "/images/samsung_sale.jpg",
    description: "Diwali Sale Samsung",
    brand: "Samsung",
    category: "Electronics",
    price: 3399.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: "8",
    name: "Diwali Sale Sony",
    image: "/images/sony_sales.jpg",
    description: "",
    brand: "Sony",
    category: "Electronics",
    price: 3399.99,
    countInStock: 0,
    rating: 5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: "9",
    name: "Diwali Sale Iqoo",
    image: "/images/iqoo_sales.jpg",
    description: "",
    brand: "Iqoo",
    category: "Electronics",
    price: 3399.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: "10",
    name: "Diwali Sale Oneplus",
    image: "/images/oneplus_sales.jpg",
    description: "",
    brand: "Oneplus",
    category: "Electronics",
    price: 3399.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
    isFeatured: true,
  },
  {
    _id: "11",
    name: "Diwali Sale Apple",
    image: "/images/iphone_sales.jpg",
    description: "",
    brand: "Apple",
    category: "Electronics",
    price: 3399.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 12,
    isFeatured: true,
  },
];

export default products;
